import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Vazirmatn } from "next/font/google";
import { Inter } from "next/font/google";

const vazir = Vazirmatn({ subsets: ["arabic"], weight: ["400", "700"] });
const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Saitzo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${vazir.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
